const plantas = [
    { idProducto: "A1B2C3D4E5", nombreProducto: "Bonsai", selectorCategoria: "ornamentales", imagen: "/src/img/1.jpg", precio: 75000, cantidad: 10, proveedor: "Vivero La Esperanza" },
    { idProducto: "F6G7H8I9J0", nombreProducto: "Cactus Mini", selectorCategoria: "cactus", imagen: "/src/img/2.jpg", precio: 15000, cantidad: 8, proveedor: "Plantas del Sol" },
    { idProducto: "K1L2M3N4O5", nombreProducto: "Helecho", selectorCategoria: "ornamentales", imagen: "/src/img/3.jpg", precio: 30000, cantidad: 15, proveedor: "Naturaleza Viva" },
    { idProducto: "P6Q7R8S9T0", nombreProducto: "Aloe Vera", selectorCategoria: "medicinales", imagen: "/src/img/4.jpg", precio: 25000, cantidad: 18, proveedor: "EcoPlantas" },
    { idProducto: "U1V2W3X4Y5", nombreProducto: "Palma Areca", selectorCategoria: "ornamentales", imagen: "/src/img/5.jpg", precio: 120000, cantidad: 12, proveedor: "Mundo Verde" },
    { idProducto: "Z6A7B8C9D0", nombreProducto: "Lavanda", selectorCategoria: "medicinales", imagen: "/src/img/6.jpg", precio: 20000, cantidad: 9, proveedor: "Vivero La Esperanza" },
    { idProducto: "E1F2G3H4I5", nombreProducto: "Rosa", selectorCategoria: "flores", imagen: "/src/img/7.jpg", precio: 18000, cantidad: 11, proveedor: "Plantas del Sol" },
    { idProducto: "J6K7L8M9N0", nombreProducto: "Suculenta", selectorCategoria: "suculentas", imagen: "/src/img/8.jpg", precio: 12000, cantidad: 17, proveedor: "Naturaleza Viva" },
    { idProducto: "O1P2Q3R4S5", nombreProducto: "Hierbabuena", selectorCategoria: "medicinales", imagen: "/src/img/9.jpg", precio: 8000, cantidad: 6, proveedor: "EcoPlantas" },
    { idProducto: "T6U7V8W9X0", nombreProducto: "Crotón", selectorCategoria: "ornamentales", imagen: "/src/img/10.jpg", precio: 35000, cantidad: 5, proveedor: "Mundo Verde" },
    { idProducto: "Y6Z7A8B9C0", nombreProducto: "Flor de Loto", selectorCategoria: "flores", imagen: "/src/img/11.jpg", precio: 45000, cantidad: 10, proveedor: "Vivero La Esperanza" },
    { idProducto: "C1D2E3F4G5", nombreProducto: "Bambú", selectorCategoria: "ornamentales", imagen: "/src/img/12.jpg", precio: 52000, cantidad: 7, proveedor: "Plantas del Sol" },
    { idProducto: "H6I7J8K9L0", nombreProducto: "Manzanilla", selectorCategoria: "medicinales", imagen: "/src/img/13.jpg", precio: 9000, cantidad: 14, proveedor: "Naturaleza Viva" },
    { idProducto: "M1N2O3P4Q5", nombreProducto: "Orquídea", selectorCategoria: "flores", imagen: "/src/img/14.jpg", precio: 65000, cantidad: 8, proveedor: "EcoPlantas" },
    { idProducto: "R6S7T8U9V0", nombreProducto: "Árbol Bonsai", selectorCategoria: "árboles", imagen: "/src/img/15.jpg", precio: 180000, cantidad: 2, proveedor: "Mundo Verde" },
    { idProducto: "W1X2Y3Z4A5", nombreProducto: "Cilantro", selectorCategoria: "medicinales", imagen: "/src/img/16.jpg", precio: 7000, cantidad: 12, proveedor: "Vivero La Esperanza" },
    { idProducto: "B6C7D8E9F0", nombreProducto: "Aguacate", selectorCategoria: "árboles", imagen: "/src/img/17.jpg", precio: 130000, cantidad: 5, proveedor: "Plantas del Sol" },
    { idProducto: "G1H2I3J4K5", nombreProducto: "Cedro", selectorCategoria: "árboles", imagen: "/src/img/18.jpg", precio: 110000, cantidad: 7, proveedor: "Naturaleza Viva" },
    { idProducto: "L6M7N8O9P0", nombreProducto: "Tulipán", selectorCategoria: "flores", imagen: "/src/img/19.jpg", precio: 28000, cantidad: 6, proveedor: "EcoPlantas" },
    { idProducto: "Q1R2S3T4U5", nombreProducto: "Menta", selectorCategoria: "medicinales", imagen: "/src/img/20.jpg", precio: 6000, cantidad: 19, proveedor: "Mundo Verde" },
    { idProducto: "V6W7X8Y9Z0", nombreProducto: "Begonia", selectorCategoria: "ornamentales", imagen: "/src/img/21.jpg", precio: 32000, cantidad: 10, proveedor: "Vivero La Esperanza" },
    { idProducto: "A1B2C3D4E6", nombreProducto: "Lirio", selectorCategoria: "flores", imagen: "/src/img/22.jpg", precio: 40000, cantidad: 5, proveedor: "Plantas del Sol" },
    { idProducto: "F6G7H8I9J1", nombreProducto: "Cedro Rojo", selectorCategoria: "árboles", imagen: "/src/img/23.jpg", precio: 115000, cantidad: 3, proveedor: "Naturaleza Viva" },
    { idProducto: "K1L2M3N4O6", nombreProducto: "Sansevieria", selectorCategoria: "ornamentales", imagen: "/src/img/24.jpg", precio: 50000, cantidad: 13, proveedor: "EcoPlantas" },
    { idProducto: "P6Q7R8S9T1", nombreProducto: "Ruda", selectorCategoria: "medicinales", imagen: "/src/img/25.jpg", precio: 9000, cantidad: 4, proveedor: "Mundo Verde" },
    { idProducto: "U1V2W3X4Y6", nombreProducto: "Jazmín", selectorCategoria: "flores", imagen: "/src/img/26.jpg", precio: 37000, cantidad: 11, proveedor: "Vivero La Esperanza" },
    { idProducto: "Z6A7B8C9D1", nombreProducto: "Albahaca", selectorCategoria: "medicinales", imagen: "/src/img/27.jpg", precio: 6000, cantidad: 8, proveedor: "Plantas del Sol" },
    { idProducto: "E1F2G3H4I6", nombreProducto: "Hortensia", selectorCategoria: "flores", imagen: "/src/img/28.jpg", precio: 55000, cantidad: 6, proveedor: "Naturaleza Viva" },
    { idProducto: "J6K7L8M9N1", nombreProducto: "Limón", selectorCategoria: "árboles", imagen: "/src/img/29.jpg", precio: 135000, cantidad: 5, proveedor: "EcoPlantas" },
    { idProducto: "O1P2Q3R4S6", nombreProducto: "Tomillo", selectorCategoria: "medicinales", imagen: "/src/img/30.jpg", precio: 10000, cantidad: 10, proveedor: "Mundo Verde" },
    { idProducto: "T6U7V8W9X1", nombreProducto: "Girasol", selectorCategoria: "flores", imagen: "/src/img/31.jpg", precio: 25000, cantidad: 8, proveedor: "Vivero La Esperanza" },
    { idProducto: "Y6Z7A8B9C1", nombreProducto: "Romero", selectorCategoria: "medicinales", imagen: "/src/img/32.jpg", precio: 7000, cantidad: 9, proveedor: "Plantas del Sol" },
    { idProducto: "C1D2E3F4G6", nombreProducto: "Geranio", selectorCategoria: "flores", imagen: "/src/img/33.jpg", precio: 21000, cantidad: 14, proveedor: "Naturaleza Viva" },
    { idProducto: "H6I7J8K9L1", nombreProducto: "Naranjo", selectorCategoria: "árboles", imagen: "/src/img/34.jpg", precio: 140000, cantidad: 4, proveedor: "EcoPlantas" },
    { idProducto: "M1N2O3P4Q6", nombreProducto: "Margarita", selectorCategoria: "flores", imagen: "/src/img/35.jpg", precio: 15000, cantidad: 7, proveedor: "Mundo Verde" },
    { idProducto: "R6S7T8U9V1", nombreProducto: "Pino", selectorCategoria: "árboles", imagen: "/src/img/36.jpg", precio: 160000, cantidad: 3, proveedor: "Vivero La Esperanza" },
    { idProducto: "W1X2Y3Z4A6", nombreProducto: "Cerezo", selectorCategoria: "árboles", imagen: "/src/img/37.jpg", precio: 145000, cantidad: 2, proveedor: "Plantas del Sol" },
    { idProducto: "B6C7D8E9F1", nombreProducto: "Lavanda Fr", selectorCategoria: "medicinales", imagen: "/src/img/38.jpg", precio: 8500, cantidad: 13, proveedor: "Naturaleza Viva" },
    { idProducto: "G1H2I3J4K6", nombreProducto: "Pepino", selectorCategoria: "medicinales", imagen: "/src/img/39.jpg", precio: 5500, cantidad: 6, proveedor: "EcoPlantas" },
    { idProducto: "L6M7N8O9P1", nombreProducto: "Caléndula", selectorCategoria: "flores", imagen: "/src/img/40.jpg", precio: 12000, cantidad: 15, proveedor: "Mundo Verde" },
    { idProducto: "Q1R2S3T4U6", nombreProducto: "Jade", selectorCategoria: "suculentas", imagen: "/src/img/41.jpg", precio: 15000, cantidad: 14, proveedor: "Vivero La Esperanza" },
    { idProducto: "V6W7X8Y9Z1", nombreProducto: "Buganvilla", selectorCategoria: "ornamentales", imagen: "/src/img/42.jpg", precio: 33000, cantidad: 5, proveedor: "Plantas del Sol" },
    { idProducto: "A1B2C3D4E7", nombreProducto: "Gardenia", selectorCategoria: "flores", imagen: "/src/img/43.jpg", precio: 40000, cantidad: 6, proveedor: "Naturaleza Viva" },
    { idProducto: "F6G7H8I9J2", nombreProducto: "Granado", selectorCategoria: "árboles", imagen: "/src/img/44.jpg", precio: 175000, cantidad: 3, proveedor: "EcoPlantas" },
    { idProducto: "K1L2M3N4O7", nombreProducto: "Limonero", selectorCategoria: "árboles", imagen: "/src/img/45.jpg", precio: 160000, cantidad: 4, proveedor: "Mundo Verde" },
    { idProducto: "P6Q7R8S9T2", nombreProducto: "Bálsamo", selectorCategoria: "medicinales", imagen: "/src/img/46.jpg", precio: 8000, cantidad: 10, proveedor: "Vivero La Esperanza" },
    { idProducto: "U1V2W3X4Y7", nombreProducto: "Anthurium", selectorCategoria: "ornamentales", imagen: "/src/img/47.jpg", precio: 47000, cantidad: 6, proveedor: "Plantas del Sol" },
    { idProducto: "Z6A7B8C9D2", nombreProducto: "Peonía", selectorCategoria: "flores", imagen: "/src/img/48.jpg", precio: 49000, cantidad: 7, proveedor: "Naturaleza Viva" },
    { idProducto: "E1F2G3H4I7", nombreProducto: "Sauce", selectorCategoria: "árboles", imagen: "/src/img/49.jpg", precio: 145000, cantidad: 2, proveedor: "EcoPlantas" },
    { idProducto: "J6K7L8M9N2", nombreProducto: "Rábano", selectorCategoria: "medicinales", imagen: "/src/img/50.jpg", precio: 5500, cantidad: 10, proveedor: "Mundo Verde" },
    { idProducto: "O1P2Q3R4S7", nombreProducto: "Ficus", selectorCategoria: "ornamentales", imagen: "/src/img/51.jpg", precio: 78000, cantidad: 8, proveedor: "Vivero La Esperanza" },
    { idProducto: "T6U7V8W9X2", nombreProducto: "Laurel", selectorCategoria: "árboles", imagen: "/src/img/52.jpg", precio: 125000, cantidad: 3, proveedor: "Plantas del Sol" },
    { idProducto: "Y6Z7A8B9C2", nombreProducto: "Verbena", selectorCategoria: "medicinales", imagen: "/src/img/53.jpg", precio: 8000, cantidad: 13, proveedor: "Naturaleza Viva" },
    { idProducto: "C1D2E3F4G7", nombreProducto: "Limoncillo", selectorCategoria: "medicinales", imagen: "/src/img/54.jpg", precio: 9000, cantidad: 5, proveedor: "EcoPlantas" },
    { idProducto: "H6I7J8K9L2", nombreProducto: "Malva", selectorCategoria: "flores", imagen: "/src/img/55.jpg", precio: 11000, cantidad: 8, proveedor: "Mundo Verde" },
    { idProducto: "M1N2O3P4Q7", nombreProducto: "Almendro", selectorCategoria: "árboles", imagen: "/src/img/56.jpg", precio: 170000, cantidad: 4, proveedor: "Vivero La Esperanza" },
    { idProducto: "R6S7T8U9V2", nombreProducto: "Magnolia", selectorCategoria: "flores", imagen: "/src/img/57.jpg", precio: 85000, cantidad: 6, proveedor: "Plantas del Sol" },
    { idProducto: "W1X2Y3Z4A7", nombreProducto: "Rábano Picante", selectorCategoria: "medicinales", imagen: "/src/img/58.jpg", precio: 5000, cantidad: 9, proveedor: "Naturaleza Viva" },
    { idProducto: "B6C7D8E9F2", nombreProducto: "Ciprés", selectorCategoria: "árboles", imagen: "/src/img/59.jpg", precio: 140000, cantidad: 4, proveedor: "EcoPlantas" },
    { idProducto: "G1H2I3J4K7", nombreProducto: "Frambuesa", selectorCategoria: "medicinales", imagen: "/src/img/60.jpg", precio: 12000, cantidad: 8, proveedor: "Mundo Verde" }
  ];